### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by avcs06** [avcs06/AutoSuggest#7]
Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at t.getSelectedTextNodes (https://avcs.pro/static/js/0-0f195273.min.js:1:1436)
    at HTMLDivElement.onKeyUpHandler (https://avcs.pro/static/js/0-0f195273.min.js:1:10623)

**Comment by avcs06** [comment]
https://github.com/avcs06/AutoSuggest/commit/925ce4cd4e61e6fee1a996250edc18b2a9f81212
